export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_COMPANY_LOGO = "UPDATE_COMPANY_LOGO";
export const UPDATE_SIDEBAR_FLAG = "UPDATE_SIDEBAR_FLAG";
export const UPDATE_APROVAL_AMOUNT = "UPDATE_APROVAL_AMOUNT";
export const TRANING_DATASET_VALUE = "TRANING_DATASET_VALUE";
