name : React CLI

on:
 push:
  branch:
    -"master"

job: 
  Build:
   run-on:ubuntu-latest
strategy:
      matrix:
        node-version: [15.x]
steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: npm test
      